version: '3.8'
services:
  mysql-container:
    image: mysql
    container_name: mysql-ha-db
    environment:      
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ehealthcare
    ports:
      - 3307:3306
    restart: always
  springboot-container:
    container_name: ehealth-app
    image: drugsforall 
    build: 
      context: ./backend/E-Health-Backend (1)/E-Health-Backend
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-ha-db
    ports:
      - 9090:9090
    restart: always
  angular-container:
    build: 
      context: ./frontend/ehealthcare-app
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    
